options:
  formatter: stylish
  merge-default-rules: true
  max-warnings: 0
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**'
    - 'coverage/**'
    - 'dist/**'
    - 'test/**'
rules:
  property-sort-order:
    - 1
    - order: concentric
